### ISSUE TITLE
Custom Connector location

### ISSUE THREAD

**Issue by deldersveld** [exasol/powerbi-exasol#1]
Readme says:
"Create a [My Documents]\Microsoft Power BI Desktop\Custom Connectors directory"

Does not work in [My Documents]. Should be from [Program Files] / [Program Files (x86)].

**Comment by ThomasBestfleisch** [comment]
Could you please post your full path, I put the extension in the following path:
`C:\Users\tb\Documents\Microsoft Power BI Desktop\Custom Connectors\`

Seems like Power BI searches in different locations for the extensions.

**Comment by deldersveld** [comment]
Yes, the Exasol connector did not appear after I placed it into C:\Users\deldersveld\Documents\Microsoft Power BI Desktop\Custom Connectors, then closed and re-opened Power BI Desktop (x64 July version). It only appeared when I placed it in C:\Program Files\Microsoft Power BI Desktop\Custom Connectors

**Comment by ThomasBestfleisch** [comment]
That's interesting, will ask my contacts at Microsoft about this behavior.

**Comment by Hugoamorar** [comment]
Hi! I do not know how/if this thread was closed. Only to say that in my case, the proposed path works: C:\Users\hmora\Documents\Microsoft Power BI Desktop\Custom Connectors

Could be that different binaries of PBI handle this in different ways?
Hugo.

**Comment by pj-spoelders** [comment]
The path should be "Users\<user>\Documents\Microsoft Power BI Desktop\Custom Connectors\". Closing this issue.
