### ISSUE TITLE
Still see "beta" on the name of connector in PBI

### ISSUE THREAD

**Issue by Hugoamorar** [exasol/powerbi-exasol#3]
Hi! Great to know that the Exasol connector is now supported!!!

Please give me some orientation. I have the october (2018) PBI version, I removed the MEZ file from the "custom connectors" folder (I was using the beta version from a while). restarted PBI but still see the "beta" version on my data sources. Any suggestion?
Hugo.
 
![exasol connector beta](https://user-images.githubusercontent.com/14944835/46980553-517e0b00-d0ab-11e8-89ae-6ce0131241b7.JPG)

**Comment by Hugoamorar** [comment]
Also, just a suggestion or request: should be nice if in the Credentials window should be added a "friendly name" to identify the connection. Eventually the user will have more than a connection string and the current IP is not friendly (just an idea).

![exasol connector beta ii](https://user-images.githubusercontent.com/14944835/46981514-141b7c80-d0af-11e8-9ac3-a383b8fdf0b1.JPG)

**Comment by ThomasBestfleisch** [comment]
Hi Hugo, I asked my contacts at Power BI and will give you a feedback ASAP.

**Comment by ThomasBestfleisch** [comment]
The driver in newer Versions of Power Bi doesn't show Beta anymore

**Comment by Hugoamorar** [comment]
Great! Thanks @thomasbestfleish!!!
