### ISSUE TITLE
Connect to Websocket

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [exasol/powerbi-exasol#31]
Was wondering whether there will be a way of connecting to Websockets.
This would allow certain situations where Proxies could be used.

**Comment by pj-spoelders** [comment]
The current adapter relies on ODBC. As far as I know there aren't any immediate plans for a connector using web sockets. I've raised the issue with product management and will get back to you on that.

**Comment by redcatbear** [comment]
Feedback from Product Management: a port to web sockets is not planned. I am closing this ticket.
