### ISSUE TITLE
identifier is ambiguous

### ISSUE THREAD

**Issue by ghost** [exasol/powerbi-exasol#6]
Hello,

I have been facing this issue wherever I have the same column name in two or more tables. I found that the query doesn't use the alias for one of these columns. Please do check and do the needful.

Error Message:
{"error":{"code":"DM_GWPipeline_Gateway_MashupDataAccessError","pbi.error":{"code":"DM_GWPipeline_Gateway_MashupDataAccessError","parameters":{},"details":[{"code":"DM_ErrorDetailNameCode_UnderlyingErrorCode","detail":{"type":1,"value":"-2147467259"}},{"code":"DM_ErrorDetailNameCode_UnderlyingErrorMessage","detail":{"type":1,"value":"<pi>ODBC: ERROR [42000] [EXASOL][EXASolution driver]identifier City is ambiguous. (Session: 1649888863845149397)"}},{"code":"DM_ErrorDetailNameCode_UnderlyingHResult","detail":{"type":1,"value":"-2147467259"}},{"code":"Microsoft.Data.Mashup.ValueError.DataSourceKind","detail":{"type":1,"value":"Exasol"}},{"code":"Microsoft.Data.Mashup.ValueError.DataSourcePath","detail":{"type":1,"value":"{\"server\":\"**********************\",\"encrypted\":\"Yes\"}"}},{"code":"Microsoft.Data.Mashup.ValueError.Reason","detail":{"type":1,"value":"DataSource.Error"}}],"exceptionCulprit":1}}}</pi>

**Comment by pj-spoelders** [comment]
Hello ghost,
Are you still having trouble with this issue? If yes, could you provide a bit more context as to how you're using the exasol connector and how to reproduce this issue?

Thank you,

Pieterjan

> Hello,
> 
> I have been facing this issue wherever I have the same column name in two or more tables. I found that the query doesn't use the alias for one of these columns. Please do check and do the needful.
> 
> Error Message:
> {"error":{"code":"DM_GWPipeline_Gateway_MashupDataAccessError","pbi.error":{"code":"DM_GWPipeline_Gateway_MashupDataAccessError","parameters":{},"details":[{"code":"DM_ErrorDetailNameCode_UnderlyingErrorCode","detail":{"type":1,"value":"-2147467259"}},{"code":"DM_ErrorDetailNameCode_UnderlyingErrorMessage","detail":{"type":1,"value":"ODBC: ERROR [42000] [EXASOL][EXASolution driver]identifier City is ambiguous. (Session: 1649888863845149397)"}},{"code":"DM_ErrorDetailNameCode_UnderlyingHResult","detail":{"type":1,"value":"-2147467259"}},{"code":"Microsoft.Data.Mashup.ValueError.DataSourceKind","detail":{"type":1,"value":"Exasol"}},{"code":"Microsoft.Data.Mashup.ValueError.DataSourcePath","detail":{"type":1,"value":"{"server":"**********************","encrypted":"Yes"}"}},{"code":"Microsoft.Data.Mashup.ValueError.Reason","detail":{"type":1,"value":"DataSource.Error"}}],"exceptionCulprit":1}}}

**Comment by pj-spoelders** [comment]
Apparently "ghost" is a deleted user on github. I'll close this ticket.
