### ISSUE TITLE
Errors when using incremental refresh with on premise exasol and power bi service

### ISSUE THREAD

**Issue by FabianOtte5946** [exasol/powerbi-exasol#7]
Hello everyone, 
Microsoft support send me here to present my issue.

We are trying to use incremental refresh in out reports which does not work.

Our environment:
- Newest PBI Desktop
- two Exasol clusters (DEV/PRD) currently running on different versions
- PRD is running on version 6.1.4
- DEV is running on version 6.2.3
- On premise data gateway running
- we are using a test-report for each exasol-environment. Both consist of a simple calendar-table
- MS-support has checked on our implementation of the incremental refresh and did not find any errors
- Refreshing within PBI Desktop works
- Our reports are working and refreshing fine after being published to the service if incremental refresh is turned off.
- We updated the Exasol ODBC drivers in our gateway ~3 weeks ago
- Multiple users working on different machines with multiple reports are having this issue

When trying to refresh a dataset with incremental refresh enabled, we get two different errors. 
PRD:
`There was an error when processing the data in the dataset.
Please try again later or contact support. If you contact support, please provide these details.
Data source errorUnable to refresh the model (id=3585480) because it references an unsupported data source.
Cluster URIWABI-WEST-EUROPE-redirect.analysis.windows.net
Activity ID0cd4ba70-fd4d-4555-8093-6782f4ee1d9c
Request ID3100f5ea-b72f-8ad7-790c-165e88f65c09
Time2020-06-10 11:14:23Z`

DEV:
`There was an error when processing the data in the dataset.
Please try again later or contact support. If you contact support, please provide these details.
Data source error{"error":{"code":"DM_GWPipeline_Gateway_MashupDataAccessError","pbi.error":{"code":"DM_GWPipeline_Gateway_MashupDataAccessError","parameters":{},"details":[{"code":"DM_ErrorDetailNameCode_UnderlyingErrorCode","detail":{"type":1,"value":"-2147467259"}},{"code":"DM_ErrorDetailNameCode_UnderlyingErrorMessage","detail":{"type":1,"value":"We're sorry, an error occurred during evaluation."}},{"code":"DM_ErrorDetailNameCode_UnderlyingHResult","detail":{"type":1,"value":"-2147467259"}}],"exceptionCulprit":1}}}
Cluster URIWABI-WEST-EUROPE-redirect.analysis.windows.net
Activity ID0cd4ba70-fd4d-4555-8093-6782f4ee1d9c
Request ID7068c88c-aeef-1b62-f650-75c975d26045
Time2020-06-10 12:11:38Z`

According to MS-Support the reason for these errors lies within this connector. Could anyone help us with this issue?

If you need any further information from us, please feel free to ask.

**Comment by frschwab** [comment]
Hi Fabian,

please use https://www.exasol.com/support to ask this question (and reference to here).
As I assume you are a paying customer, then you should have access there.

If possible, please provide there also the odbc logs:
https://docs.exasol.com/connect_exasol/drivers/odbc/using_odbc.htm
There is a description for EXALOGFILE and LOGMODE. I think DEFAULT should be ok for a first look.

Did this error show up for the first time after you updated the ODBC driver? If yes, what was the old version of the ODBC driver?
What version of the ODBC driver are you using now?

That are probably the question support would ask anyway ;-)

Best regards,
Franz

**Comment by FabianOtte5946** [comment]
Thank you Franz, I created an issue in your jira-board.

**Comment by pj-spoelders** [comment]
This issue's been resolved. Apparently an issue with incremental refresh on the service side.
